// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FindAnswersController from "./find_answers_controller"
application.register("find-answers", FindAnswersController)

import FindWordsController from "./find_words_controller"
application.register("find-words", FindWordsController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ListenActivityController from "./listen_activity_controller"
application.register("listen-activity", ListenActivityController)

import MatchActivityController from "./match_activity_controller"
application.register("match-activity", MatchActivityController)

import MatchTokensActivityController from "./match_tokens_activity_controller"
application.register("match-tokens-activity", MatchTokensActivityController)

import MultiselectController from "./multiselect_controller"
application.register("multiselect", MultiselectController)

import PopoverTranslationController from "./popover_translation_controller"
application.register("popover-translation", PopoverTranslationController)

import SortPhrasesActivityController from "./sort_phrases_activity_controller"
application.register("sort-phrases-activity", SortPhrasesActivityController)

import SpeakActivityController from "./speak_activity_controller"
application.register("speak-activity", SpeakActivityController)

import WordOrderActivityController from "./word_order_activity_controller"
application.register("word-order-activity", WordOrderActivityController)

import SpeechRecognitionController from "./speech_recognition_controller"
application.register("speech-recognition", SpeechRecognitionController)

import MainVideoPlayerController from "./main_video_player_controller"
application.register("main-video-player", MainVideoPlayerController)

import ActivityNavigationController from './activity_navigation_controller';
application.register('activity-navigation', ActivityNavigationController);

import ProgressTrackerController from './progress_tracker_controller';
application.register('progress-tracker', ProgressTrackerController)

import SwiperController from './swiper_controller.js';
application.register('swiper', SwiperController);

import WatchVideoActivityController from './watch_video_activity_controller.js';
application.register('watch-video-activity', WatchVideoActivityController);

import MiniPlayerController from './mini_player_controller.js';
application.register('mini-player', MiniPlayerController);

import ScrollIntoViewController from './scroll_into_view_controller.js';
application.register('scroll-into-view', ScrollIntoViewController);