development:
  adapter: postgresql
  encoding: unicode
  database: langlets_development
  username: postgres
  password: postgres
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

test:
  adapter: postgresql
  encoding: unicode
  database: langlets_test
  username: postgres
  password: postgres
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
