- title: "Gauvain Sers - Ton jean bleu (Lyric Video)"
  url: "https://www.youtube.com/watch?v=ImqYzlZmLkg"
  clip_language: "French"

- title: "Le Renard et la Cigogne"
  url: "https://www.youtube.com/watch?v=XuabXPaO41U"
  clip_language: "French"

- title: "Le Loup et l'Agneau"
  url: "https://www.youtube.com/watch?v=WmZKb5WlR8g"
  clip_language: "French"

- title: "Jours fériés"
  url: "https://www.youtube.com/watch?v=abh8RaL8Jac"
  clip_language: "French"

- title: "León Gieco - Solo Le Pido A Dios"
  url: "https://www.youtube.com/watch?v=x5PJoP9x-Ys"
  clip_language: "Spanish"

- title: "El Problema con el Himno de España"
  url: "https://www.youtube.com/watch?v=6NlSpDcdFSQ"
  clip_language: "Spanish"

- title: "Con la Misma Piedra"
  url: "https://www.youtube.com/watch?v=BoD6NCXMKuk"
  clip_language: "Spanish"

- title: "El fletero previa a la final"
  url: "https://www.youtube.com/watch?v=W4dzbvxmMwg"
  clip_language: "Spanish"