[Unit]
Wants=surfshark-wg-netns@cy-nic.service
Wants=surfshark-wg-netns@gr-ath.service
Wants=surfshark-wg-netns@no-osl.service
Wants=surfshark-wg-netns@co-bog.service
After=surfshark-wg-netns@cy-nic.service
After=surfshark-wg-netns@gr-ath.service
After=surfshark-wg-netns@no-osl.service
After=surfshark-wg-netns@co-bog.service
